default:
    - override hydra/output: local
    - override hydra/launcher: local

data:
  pickle_fn: assets/cloud-dataset-scooping/scooping_parsed_with_embeddings_moco_conv5_robocloud.pkl
  subsample_period: 1
  in_dim: 7
  out_dim: 7
  H: 50 # horizon of actions to predict each time
  top_k: null
  images:
    cameras: []
    im_h: 480
    im_w: 640
    per_img_out: 128
    crop: True
  noise: 0.0

agent:
  type: 'bcimage_pre'
  vision_model: 'moco_conv5_robocloud'
  vision_model_path: 'assets/BYOL_18v2_fixed_100.pt' # only used when vision_model is 'byol'
  description: NA
  hidden_dim: 128

training:
  lr: 1e-3
  seed: 0
  epochs: 80
  device: 'cuda:0'
  batch_size: 128
  save_every_x_epoch: 10

debug: False
